from app.routes.auth import auth_bp
from app.routes.notices import notices_bp
from app.routes.users import users_bp
from app.routes.departments import departments_bp
from app.routes.batches import batches_bp
from app.routes.academic_years import academic_years_bp
from app.routes.representations import representations_bp
from app.routes.student_history import student_history_bp
from app.routes.admin import admin_bp