from app.models.academic_year import AcademicYear
from app.models.batch import Batch
from app.models.department import Department
from app.models.role import Role
from app.models.user import User
from app.models.student_history import StudentAcademicHistory
from app.models.representation import Representation
from app.models.notice import Notice
from app.models.notice_audience import NoticeAudience